name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON beast... RAAR" >> dragon.txt

    - name: Upload Dragon test file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        #path: path/to/artifact/world.txt
        path: dragon.txt
      

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon test file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
        #path: path/to/artifact/world.txt
        

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

  
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon test file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
        #path: path/to/artifact/world.txt

    - name: Read File
      run: cat dragon.txt

    - name: deploy
      run: echo Deploying .. .. ..

    
      