name: Exploring Variables and Secrets

on: push

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - name: Docker Build
  #     run: docker build -t docker.io/dockerUsername/imagetagname:latest
    
  #   - name: Docker Login
  #     run: docker login --username=dockerUsername --password=abracadabra

  #   - name: Docker Publish
  #     run: docker push docker.io/dockerUsername/imageName:latest

  # deploy:
  # needs: docker
  # runs-on: ubuntu-latest
  # steps:
  # - name: Docker Run
  #   run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

###############Environment vriables at step level#######################

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: haroldo1414
        IMAGE_NAME: github-actions-nginx
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        
    - name: Docker Login
      env:
        DOCKER_PASSWORD: abracadabra
        DOCKER-USERNAME: haroldo1414
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publish
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: haroldo1414
        IMAGE_NAME: github-actions-nginx
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker Run
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER-USERNAME: haroldo1414
        IMAGE_NAME: github-actions-nginx
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
##################Environment vriables at job level#######################
  docker:
    env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: haroldo1414
        IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        
    - name: Docker Login
      env:
        DOCKER_PASSWORD: abracadabra
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publish
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    env:
      CONTAINER_REGISTRY: docker.io
      DOCKER-USERNAME: haroldo1414
      IMAGE_NAME: github-actions-nginx
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

##################Environment vriables at workflow level#######################
# name: Exploring Variables and Secrets

# on: push

# jobs:
#     env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: haroldo1414
#         IMAGE_NAME: github-actions-nginx

#   docker: 
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       run: echo docker build -t ${{ env.CONTAINER_REGISTRY }} /$DOCKER_USERNAME/$IMAGE_NAME:latest
        
#     - name: Docker Login
#       env:
#         DOCKER_PASSWORD: abracadabra
#       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#     - name: Docker Publish
#       run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: docker Run
#       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest