name: Workflow filters and Activities

on:
  workflow_dispatch: 
  push:
    branches: 
       - main
       - '!feature/*'   # ignoring pushing to any branch name starting with feature using        
        # branches-ignore: 
        #   - feature/*   #feature/add-music, feature/updateImages
        #   - test/**     # test/ui/index, test/checkout/payment/
  
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:       # workflow will only run when pull request that includes a change on any file either than READne.md
      - README.md
    branches: 
      - main            # configures your workflow to only run on pull requests that target specific branches

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello workflow
      run: echo "hello workflow filter"